feat: add MoonPhase view
VChet/tamriel-calendar pull request #21
Opened 2024-11-29 17:27 UTC by VChet

2024-11-29 19:49 UTC, rudnovd requested changes

2024-11-29 19:49 UTC, rudnovd commented on src/views/MoonPhaseView.vue
> +      <div class="moon-phase-view__moons">
Можно без дополнительного блока? Не сильно верстку усложнит.
```css
h1 {
  margin-bottom: 2.125rem;
  grid-column: 1 / -1;
}
.container {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem
}
```

2024-11-29 19:49 UTC, rudnovd commented on src/views/MoonPhaseView.vue
> +    <section class="container">
Сложнее читается?
```html
<section class="container">
  <h1>{{ $t("moonPhase") }}</h1>
  <div v-for="(phase, moon) in phases" :key="moon" class="moon-phase-view__moon">
    {{ $t(`moonPhasePage.phases[${phase}]`) }}
    <img :src="`/img/moons/${moon}/${moon}_${MoonPhase[phase]}.webp`" :alt="MoonPhase[phase]">
    <h2>{{ $t(`moonPhasePage.${moon}`) }}</h2>
    </div>
  </section>
```

2024-11-29 19:49 UTC, rudnovd commented on src/views/MoonPhaseView.vue
> +const phases = computed(calculateLunarPhases);
Похоже `computed` влиять ни на что не будет, компонент рендерится при переходе на страницу и думаю каких-то случаев для пересчета поймать невозможно, тем более, что реактивных зависимостей нет.

2024-11-29 19:49 UTC, rudnovd commented on src/components/MainNav.vue
> +];
as const?

2024-11-29 19:49 UTC, rudnovd commented on src/components/MainNav.vue
> +            :class="{ 'nav-tab--active': pages.includes(currentRoute) }"
Может интересовался раньше, но забыл, не хочешь children роутера поменять чтобы можно было сразу сразу `active-class="nav-tab--active"` на router-link прокинуть?

2024-11-29 19:49 UTC, rudnovd commented on src/components/MainNav.vue
> +            :class="{ 'nav-tab--active': pages.includes(currentRoute) }"
Если не хочешь, то можно добавить еще проверку
`:class="{ 'nav-tab--active': currentRoute === route || pages.includes(currentRoute) }"` и убрать из `tabs` первый элемент массива для каждой вкладки.

2024-11-30 10:05 UTC, VChet commented on src/views/MoonPhaseView.vue
> +      <div class="moon-phase-view__moons">
Не хочется в container добавлять еще стили кроме стандартных. И я бы сетку контента отделял от заголовка, может стили h1 вынесу в глобальные и нужно чтобы margin были одинаковые здесь и на странице знаков.

2024-11-30 10:07 UTC, VChet commented on src/views/MoonPhaseView.vue
> +    <section class="container">
Кажется, что использовать v-for для 2 элементов — перебор, хоть они и одинаковые 🤔

2024-11-30 10:07 UTC, VChet commented on src/views/MoonPhaseView.vue
> +const phases = computed(calculateLunarPhases);
Ну хотелось бы, чтобы пересчитывалось при изменении currentDayOfYear, но наверно этого не произойдет

2024-11-30 10:09 UTC, VChet commented on src/components/MainNav.vue
> +];
pages становится константой и не получится сравнить currentRoute: string с кортежем фиксированных строк. Но вроде ts-reset это фиксить должен, попробую позже

2024-11-30 10:20 UTC, VChet commented on src/components/MainNav.vue
> +            :class="{ 'nav-tab--active': pages.includes(currentRoute) }"
> Может интересовался раньше, но забыл, не хочешь children роутера поменять чтобы можно было сразу сразу `active-class="nav-tab--active"` на router-link прокинуть?

Если добавлять в children, то компонент будет рендериться внутри вложенного router-view.

> Если не хочешь, то можно добавить еще проверку `:class="{ 'nav-tab--active': currentRoute === route || pages.includes(currentRoute) }"` и убрать из `tabs` первый элемент массива для каждой вкладки.

Кажется так сложнее воспринимается, когда явно не указываем все названия. Вместо создания таких массивов, может лучше будет через meta теги рута описывать к какой странице относится?

2024-11-30 10:52 UTC, VChet commented on src/components/MainNav.vue
> +];
Указал тип с readonly

2024-11-30 12:53 UTC, rudnovd commented on src/views/MoonPhaseView.vue
> +    <section class="container">
А какие-то новые варианты могут появиться позже? Если нет, то может тогда и формулы расчета как-то проще написать можно? Делить на какую-нибудь общую константу и при округлении к ближайшему числу маппинга обращаться?

2024-11-30 14:46 UTC, VChet commented on src/views/MoonPhaseView.vue
> +    <section class="container">
Маловероятно, но может больше фаз появится. Переписал на получение ближайшего индекса

2024-11-30 17:10 UTC, rudnovd approved these changes

2024-11-30 17:11 UTC, merged